In [1]:
pwd

'C:\\Users\\iibm\\Desktop\\Project Python'

In [2]:
print("Workshop on Python")

Workshop on Python


In [3]:
print('zhi')

zhi


In [4]:
print('a \'a\'')

a 'a'


In [5]:
print('''b 'bittu' ''')

b 'bittu' 


In [6]:
print('''
data
science
zhi''')


data
science
zhi


# Arithmetic Operator

# plus

In [7]:
2+6

8

In [8]:
78-56

22

In [9]:
2*6

12

In [10]:
2**9

512

In [11]:
4/2

2.0

In [12]:
4//2

2

In [13]:
4.2//2

2.0

In [14]:
2e2

200.0

In [15]:
5*5+8*2

41

In [16]:
(5+5)*2

20

In [17]:
x=20
x

20

In [18]:
x=20
x

20

In [19]:
type(x)

int

In [20]:
print(type(x))

<class 'int'>


In [21]:
s="workshop"

In [22]:
s

'workshop'

# Slicing and Indexing

s[start:end:step] 

In [23]:
s[:]

'workshop'

In [24]:
s[: :]

'workshop'

In [25]:
s[5]

'h'

In [26]:
s[:5]

'works'

In [27]:
s[3:]

'kshop'

In [28]:
 s[: :2]

'wrso'

In [29]:
s[: :-1]

'pohskrow'

In [30]:
s[-3:-2]

'h'

# Methods

In [31]:
s.upper()

'WORKSHOP'

In [32]:
s=s.upper()

In [33]:
s

'WORKSHOP'

 split

In [34]:
'data'.split()

['data']

In [35]:
'A B C D'.split()

['A', 'B', 'C', 'D']

In [36]:
'A B C D'.split(C)

NameError: name 'C' is not defined

In [ ]:
'A B C D'.split('C')

In [ ]:
s.split('S')

# Print Property

In [ ]:
name='virat'
run=100

In [ ]:
print(name+str(run))

# Formating

In [ ]:
print('this is a %s pen' %("ram"))


# List

In [ ]:
list='A B C D'.split()

In [ ]:
list

In [ ]:
list=['a',5,5.5]

In [ ]:
list

In [ ]:
type(list)

# slicing and Indexing

In [ ]:
list[1]

In [ ]:
list[0:2]

In [ ]:
list[0:3:1]

In [ ]:
list[0:3:2]

In [ ]:
list*2

In [ ]:
list=list+['a']

In [ ]:
list

# list Method

In [ ]:
l=[1,2,3,4,5]

In [ ]:
l

In [ ]:
l.append('A B C D'.split())

In [ ]:
l


In [ ]:
l.append('A')

In [ ]:
l

In [ ]:
list1=[1,2,3,4,5]

In [ ]:
list1

In [ ]:
print(list1)

In [ ]:
print(type(list1))

In [ ]:
list1.append("Bittu Kumar")

In [ ]:
list1

In [ ]:
list1.append('zhi')

In [ ]:
list1

In [ ]:
list.pop(4)

In [ ]:
l1=[1,2,3]
l2=[4,5,6]
l3=[7,8,9]

In [ ]:
matrix=[l1,l2,l3]

In [ ]:
matrix

In [ ]:
type(matrix)

In [ ]:
matrix[1][0]

In [ ]:
len(matrix)

# Tuple

In [ ]:
t1=(11,2,3)
t1

In [ ]:
type(t1)

In [ ]:
print(type(t1))

In [ ]:
t1[1]

In [ ]:
t1[-1]

# Tuple Method

In [ ]:
t1.index(2)

In [ ]:
t1.index(3)

In [ ]:
t1.count(3)

# Dictionary

In [ ]:
disc1={
    1:'a', 2:'b', 3:'c'
}

In [ ]:
disc1

In [ ]:
type(disc1)

In [ ]:
print(type(disc1))

In [ ]:
disc1[1]

In [ ]:
disc1[2]

In [ ]:
disc1[4]='Bittu'

In [ ]:
disc1

# Nested Dictionary

In [ ]:
disc1={1:'a', 2:'b',
      'key1':{
          1:'a', 2:'hello', 3:'c'
      },
      3:'c'}


In [ ]:
disc1['key1'][2]

# Method

In [ ]:
disc1.keys()

In [ ]:
disc1.values()

In [ ]:
disc1.items()

# set 

Unordered Collection

In [ ]:
 x=set()

In [ ]:
x

In [ ]:
type(x)

In [ ]:
print(type(x))

In [ ]:
x.add(1)

In [ ]:
x

In [ ]:
list2=[1,2,3,1,2,3,2,2,3,4]

In [ ]:
list2

In [ ]:
set(list2)

# Boolean  

In [ ]:
True

In [ ]:
False

In [ ]:
None

# Q1: Reassign 'hello' in this nested list to say 'goodbye' insted;
list3=[1,2,[3,4,'hello']]

In [ ]:
list3=[1,2,[3,4,'hello']]

In [ ]:
list3

In [ ]:
list3[2][2]

In [ ]:
list3[2][2]="goodbye"

In [ ]:
list3

# Membership Operator

In [ ]:
m='iibm patna'

In [ ]:
m

In [ ]:
't' in m

In [ ]:
'x' in  m

In [ ]:
x=100

In [ ]:
y=100

In [ ]:
x is y

In [ ]:
x is not y

In [ ]:
list1=[1,2,3]

In [ ]:
list2=[1,2,3]


In [ ]:
list1 == list2

# Numerical Python

In [ ]:
import numpy as np

In [ ]:
x=[1,2,3,4,5]
x

In [ ]:
type(x)

In [ ]:
y=np.array(x)

In [ ]:
type(y)

In [ ]:
x2=[1,2,3,'NIELIT',3.4]

In [ ]:
np.array(x2)

# Linspace

In [ ]:
np.linspace(start=0, stop=20, num=10, endpoint=False,retstep=True)

In [ ]:
np.linspace(start=0,stop=20,num=10,endpoint=True,retstep=True)

# Arange

In [ ]:
np.arange(start=0,stop=50,step=5)

In [ ]:
np.arange(0,10,2)

In [ ]:
np.arange(5,10)

# Create 3D Array

In [ ]:
z=[[1,2,3],[4,5,6],[7,8,9]]

In [ ]:
z

In [ ]:
y=np.array(z)

In [ ]:
y

In [ ]:
np.ones((3,3))

In [ ]:
np.zeros((4,5))

In [ ]:
np.eye(4)

# Reshaping

In [ ]:
x=np.array([0,1,2,3,4,5,6,7,8,9])

In [ ]:
x

# Convert to 5*2

In [ ]:
x.reshape((5,2))

In [ ]:
  x.reshape((1,10))

In [ ]:
x.reshape((10,1))

# sliceing

In [ ]:
a=np.arange(10)

In [ ]:
a

In [ ]:
s=slice(2,7)

In [ ]:
a[s]

In [ ]:
s1=slice(2,7,2)

In [ ]:
a[s1]

In [ ]:
a[2:7]

In [ ]:
a[2:7:2]

# Random Number Generation

In [ ]:
np.random.rand(5)

In [ ]:
np.random.rand(5)

# Normal Distribution

In [ ]:
np.random.randn(5,4)

# Randint

In [ ]:
np.random.randint(low=0,high=100)

In [ ]:
# 4 digit Random Number
np.random.randint(low=1000,high=9999)

In [ ]:
np.random.randint(low=1000,high=9999,size=10)

# Seed 

In [ ]:
np.random.seed(23)

In [ ]:
np.random.rand(4)

In [ ]:
np.random.seed(23)

In [ ]:
np.random.rand(4)

# Brodcasting 

In [37]:
import numpy as np


In [38]:
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
arr/10

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [40]:
l1=[0,1,2,3,4,5,6,7,8,9]

In [41]:
l1

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [42]:
l1[1]/10

0.1

In [43]:
arr*5

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [44]:
arr-1

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [45]:
arr>5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [46]:
arr[arr>5]

array([6, 7, 8, 9])

In [47]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
arr1=arr[0:6]

In [49]:
arr1

array([0, 1, 2, 3, 4, 5])

In [50]:
arr[:5]

array([0, 1, 2, 3, 4])

In [51]:
arr[4:]

array([4, 5, 6, 7, 8, 9])

In [52]:
arr[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
arr1[:]=555

In [54]:
arr1

array([555, 555, 555, 555, 555, 555])

In [55]:
arr

array([555, 555, 555, 555, 555, 555,   6,   7,   8,   9])

In [56]:
arr1

array([555, 555, 555, 555, 555, 555])

In [57]:
arr

array([555, 555, 555, 555, 555, 555,   6,   7,   8,   9])

# Copy of an Array

In [58]:
arr2=arr.copy()

In [59]:
arr2

array([555, 555, 555, 555, 555, 555,   6,   7,   8,   9])

#  Python list vs Numpy Array

In [60]:
size=1000
x=range(size)
y=range(size)

In [61]:
%%timeit
[x[i]*y[i] for i in range(size)] 

227 µs ± 2.88 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [62]:
x1=np.arange(size)
y1=np.arange(size)

In [63]:
%%timeit
x1*y1

1.26 µs ± 8.4 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


#  Insert


In [65]:
b=np.array([[1,2,3],[4,5,6],[7,8,9]])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [78]:
b1=np.insert(b,1,[15,16,17],axis=0)

In [79]:
b2=np.insert(b,1,[15,16,17],axis=1)

In [80]:
b2

array([[ 1, 15,  2,  3],
       [ 4, 16,  5,  6],
       [ 7, 17,  8,  9]])

# Matrix

In [76]:
x=np.matrix('1,2,3;4,5,6;7,8,9')
x

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [81]:
x[2,1]=-7

In [82]:
x

matrix([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7, -7,  9]])

In [83]:
x[2,2]=-9

In [84]:
x

matrix([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7, -7, -9]])

In [85]:
arr=np.array([[1,2,3],[4,5,6,],[7,8,9]])

In [86]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [93]:
arr[2,1]=-7
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7, -7,  9]])

In [91]:
np.insert(arr,2,2)

array([1, 2, 2, 3, 4, 5, 6, 7, 8, 9])

In [94]:
x*x

matrix([[ 30,  -9, -12],
        [ 66,  -9, -12],
        [-84,  42,  60]])

In [95]:
arr*arr

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 49, 81]])

In [96]:
arr@arr

array([[ 30,  -9,  42],
       [ 66,  -9,  96],
       [ 42, -84,  60]])

# Storage in File 

In [97]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7, -7,  9]])

In [98]:
np.savetxt('a.txt',arr)

In [100]:
np.savetxt('a.txt',arr,delimiter=',')

In [101]:
np.loadtxt('a.txt',delimiter=',')

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7., -7.,  9.]])

In [102]:
np.save('data.npy',arr)

In [103]:
np.load('data.npy')

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7, -7,  9]])

In [104]:
a=np.arange(10)

In [105]:
np.savez('both.npz',arr,a)

In [106]:
z=np.load('both.npz')

In [107]:
z.files

['arr_0', 'arr_1']

In [109]:
z[z.files[0]]

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7, -7,  9]])

In [110]:
z[z.files[1]]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Statistics Function

In [1]:
import numpy as np

In [2]:
x=np.array([[1,2,3],[2,4,6],[90,100,50]])

In [3]:
x

array([[  1,   2,   3],
       [  2,   4,   6],
       [ 90, 100,  50]])

In [4]:
np.amin(x)

1

In [5]:
np.amax(x)

100

In [6]:
np.amin(x,axis=1)

array([ 1,  2, 50])

In [7]:
np.amin(x,axis=0)

array([1, 2, 3])

In [8]:
np.amax(x,axis=1)

array([  3,   6, 100])

In [9]:
x

array([[  1,   2,   3],
       [  2,   4,   6],
       [ 90, 100,  50]])

In [10]:
np.average(x)

28.666666666666668

# Weighted average

In [11]:
w=[1,2,3]

In [12]:
np.average(x,weights=w,axis=0)

array([45.83333333, 51.66666667, 27.5       ])

In [13]:
np.average(x,weights=w,axis=1)

array([ 2.33333333,  4.66666667, 73.33333333])

In [14]:
np.mean(x)

28.666666666666668

In [15]:
np.mean(x[0])

2.0

In [16]:
np.mean(x[1])

4.0

In [17]:
np.mean(x[2])

80.0

In [18]:
np.mean(x[2])

80.0

In [19]:
np.mean(x,axis=0)

array([31.        , 35.33333333, 19.66666667])

In [20]:
np.mean(x,axis=1)

array([ 2.,  4., 80.])

In [21]:
np.median(x)

4.0

In [22]:
np.median(x,axis=1)

array([ 2.,  4., 90.])

In [23]:
np.median(x,axis=0)

array([2., 4., 6.])

In [24]:
np.var(x)

1474.888888888889

In [25]:
np.std(x)

38.4042821686448